export type Product = {
    id: number,
    nome: string,
    categoria: string,
    slug: string,
    imagem: string,
    descricao: string,
    material: string,
    preco: number,
}

const CATEGORY_IMAGES: Record<string, string[]> = {
    'Roupas, Calçados e Acessórios': [
        '/img/Categorias/Roupas, Calçados e Acessórios/moda.jpg',
        '/img/Categorias/Roupas, Calçados e Acessórios/roupa2.webp',
        '/img/Categorias/Roupas, Calçados e Acessórios/roupa3.webp',
        '/img/Categorias/Roupas, Calçados e Acessórios/roupa4.jpg',
        '/img/Categorias/Roupas, Calçados e Acessórios/roupa4.webp',
    ],
    'Automotivo': [
        '/img/Categorias/Automotivo/automotivo.jpg',
        '/img/Categorias/Automotivo/automotivo2.webp',
        '/img/Categorias/Automotivo/automotivo3.webp',
        '/img/Categorias/Automotivo/automotivo4.webp',
        '/img/Categorias/Automotivo/automotivo5.webp',
    ],
    'Beleza e Cuidados Pessoais': [
        '/img/Categorias/Beleza e Cuidados Pessoais/batom.jpg',
        '/img/Categorias/Beleza e Cuidados Pessoais/beleza.webp',
        '/img/Categorias/Beleza e Cuidados Pessoais/beleza2.webp',
        '/img/Categorias/Beleza e Cuidados Pessoais/beleza3.webp',
        '/img/Categorias/Beleza e Cuidados Pessoais/beleza4.jpg',
    ],
    'Brinquedos e Jogos': [
        '/img/Categorias/Brinquedos e Jogos/brinquedos.jpg',
        '/img/Categorias/Brinquedos e Jogos/jogos.webp',
        '/img/Categorias/Brinquedos e Jogos/jogos2.webp',
        '/img/Categorias/Brinquedos e Jogos/jogos3.webp',
        '/img/Categorias/Brinquedos e Jogos/jogos4.webp',
    ],
    'Casa, Jardim e Limpeza': [
        '/img/Categorias/Casa, Jardim, e Limpeza/ventilador.jpg',
        '/img/Categorias/Casa, Jardim, e Limpeza/casa.webp',
        '/img/Categorias/Casa, Jardim, e Limpeza/casa2.webp',
        '/img/Categorias/Casa, Jardim, e Limpeza/casa3.webp',
        '/img/Categorias/Casa, Jardim, e Limpeza/casa4.webp',
        '/img/Categorias/Casa, Jardim, e Limpeza/casa5.webp',
    ],
    'Cozinha': [
        '/img/Categorias/Cozinha/cozinha.jpg',
        '/img/Categorias/Cozinha/cozinha.webp',
        '/img/Categorias/Cozinha/cozinha2.webp',
        '/img/Categorias/Cozinha/cozinha3.webp',
        '/img/Categorias/Cozinha/cozinha4.webp',
        '/img/Categorias/Cozinha/cozinha5.webp',
    ],
    'Eletrônicos, TV e Áudio': [
        '/img/Categorias/Eletrônicos, TV, Áudio/eletrodomesticos.jpg',
        '/img/Categorias/Eletrônicos, TV, Áudio/tv1.webp',
        '/img/Categorias/Eletrônicos, TV, Áudio/tv2.webp',
        '/img/Categorias/Eletrônicos, TV, Áudio/tv3.jpg',
        '/img/Categorias/Eletrônicos, TV, Áudio/tv4.webp',
    ],
    'Esportes, Aventura e Lazer': [
        '/img/Categorias/Esportes, Aventura e Lazer/Esportes.jpg',
        '/img/Categorias/Esportes, Aventura e Lazer/esportes2.webp',
        '/img/Categorias/Esportes, Aventura e Lazer/esportes3.webp',
        '/img/Categorias/Esportes, Aventura e Lazer/esportes4.webp',
        '/img/Categorias/Esportes, Aventura e Lazer/esportes5.webp',
    ],
    'Ferramentas e Construção': [
        '/img/Categorias/Ferramentas e Construção/ferramentas.jpg',
        '/img/Categorias/Ferramentas e Construção/ferramentas2.webp',
        '/img/Categorias/Ferramentas e Construção/ferramentas3.webp',
        '/img/Categorias/Ferramentas e Construção/ferramentas4.webp',
        '/img/Categorias/Ferramentas e Construção/ferramentas5.webp',
    ],
    'Games e Consoles': [
        '/img/Categorias/Games e Consoles/games.jpg',
        '/img/Categorias/Games e Consoles/games.webp',
        '/img/Categorias/Games e Consoles/games2.webp',
        '/img/Categorias/Games e Consoles/games3.webp',
        '/img/Categorias/Games e Consoles/games4.webp',
        '/img/Categorias/Games e Consoles/games5.webp',
    ],
    'Livros': [
        '/img/Categorias/Livros/livros.jpg',
        '/img/Categorias/Livros/livros1.webp',
        '/img/Categorias/Livros/livros2.jpg',
        '/img/Categorias/Livros/livros3.jpg',
        '/img/Categorias/Livros/livros4.jpg',
    ],
    'Papelaria e Escritório': [
        '/img/Categorias/Papelaria e Escritório/papel.webp',
        '/img/Categorias/Papelaria e Escritório/papel2.webp',
        '/img/Categorias/Papelaria e Escritório/papel3.webp',
        '/img/Categorias/Papelaria e Escritório/papel4.webp',
        '/img/Categorias/Papelaria e Escritório/papel5.webp',
    ],
    'Bebês':[
        '/img/Categorias/Bebês/bebes.webp',
        '/img/Categorias/Bebês/bebes2.webp',
        '/img/Categorias/Bebês/bebes3.webp',
        '/img/Categorias/Bebês/bebes4.webp',
        '/img/Categorias/Bebês/bebes5.webp',
    ],
    'Bolsas, Malas e Mochilas':[
        '/img/Categorias/Bolsas, Malas e Mochilas/mala.webp',
        '/img/Categorias/Bolsas, Malas e Mochilas/mala2.webp',
        '/img/Categorias/Bolsas, Malas e Mochilas/mala3.webp',
        '/img/Categorias/Bolsas, Malas e Mochilas/mala4.webp',
    ],
    'Celulares e Comunicação':[
        '/img/Categorias/Celulares e Comunicação/celular.jpg',
        '/img/Categorias/Celulares e Comunicação/celular2.webp',
        '/img/Categorias/Celulares e Comunicação/celular3.webp',
        '/img/Categorias/Celulares e Comunicação/celular4.webp',
    ],
    'Computadores e Informática':[
        '/img/Categorias/Computadores e Informática/computador.jpg',
        '/img/Categorias/Computadores e Informática/computador2.webp',
        '/img/Categorias/Computadores e Informática/computador3.webp',
        '/img/Categorias/Computadores e Informática/computador4.jpg',
    ],
    'Filmes, Séries e Música':[
        '/img/Categorias/Filmes, Séries e Música/filmes.jpg',
        '/img/Categorias/Filmes, Séries e Música/filmes2.webp',
        '/img/Categorias/Filmes, Séries e Música/filmes3.webp',
        '/img/Categorias/Filmes, Séries e Música/filmes4.jpg',
        '/img/Categorias/Filmes, Séries e Música/filmes5.jpg',
    ],
    'Pet Shop':[
        '/img/Categorias/Pet Shop/pet.webp',
        '/img/Categorias/Pet Shop/pet2.webp',
        '/img/Categorias/Pet Shop/pet3.webp',
        '/img/Categorias/Pet Shop/pet4.webp',
        '/img/Categorias/Pet Shop/pet5.webp',
        '/img/Categorias/Pet Shop/Pets.jpg',
    ],
};

function applyCategoryImages(list: Product[]): Product[] {
    const counters: Record<string, number> = {};
    return list.map((product) => {
        const images = CATEGORY_IMAGES[product.categoria];
        if (!images?.length) return product;
        const index = counters[product.categoria] ?? 0;
        counters[product.categoria] = index + 1;
        return {
            ...product,
            imagem: images[index % images.length],
        };
    });
}

const defaultDescricao =
    'Produto da categoria, pensado para o dia a dia e com ótima durabilidade. ' +
    'Entrega um excelente custo-benefício e uma experiência prática para uso contínuo.';

const rawProducts: Product[] = [
    // Moda (1-9)
    {
        id: 1,
        nome: 'Moda Essencial 01',
        categoria: 'Roupas, Calçados e Acessórios',
        slug: 'roupas-calcados-acessorios',
        imagem: '/img/Categorias/Roupas, Calçados e Acessórios/moda.jpg',
        descricao: defaultDescricao,
        material: 'Têxtil e aviamentos',
        preco: 69.9,
    },
    {
        id: 2,
        nome: 'Moda Essencial 02',
        categoria: 'Roupas, Calçados e Acessórios',
        slug: 'roupas-calcados-acessorios',
        imagem: '/img/Categorias/Roupas, Calçados e Acessórios/moda.jpg',
        descricao: defaultDescricao,
        material: 'Têxtil e aviamentos',
        preco: 72.65,
    },
    {
        id: 3,
        nome: 'Moda Essencial 03',
        categoria: 'Roupas, Calçados e Acessórios',
        slug: 'roupas-calcados-acessorios',
        imagem: '/img/Categorias/Roupas, Calçados e Acessórios/moda.jpg',
        descricao: defaultDescricao,
        material: 'Têxtil e aviamentos',
        preco: 75.4,
    },
    {
        id: 4,
        nome: 'Moda Essencial 04',
        categoria: 'Roupas, Calçados e Acessórios',
        slug: 'roupas-calcados-acessorios',
        imagem: '/img/Categorias/Roupas, Calçados e Acessórios/moda.jpg',
        descricao: defaultDescricao,
        material: 'Têxtil e aviamentos',
        preco: 78.15,
    },
    {
        id: 5,
        nome: 'Moda Essencial 05',
        categoria: 'Roupas, Calçados e Acessórios',
        slug: 'roupas-calcados-acessorios',
        imagem: '/img/Categorias/Roupas, Calçados e Acessórios/moda.jpg',
        descricao: defaultDescricao,
        material: 'Têxtil e aviamentos',
        preco: 80.9,
    },
    {
        id: 6,
        nome: 'Moda Essencial 06',
        categoria: 'Roupas, Calçados e Acessórios',
        slug: 'roupas-calcados-acessorios',
        imagem: '/img/Categorias/Roupas, Calçados e Acessórios/moda.jpg',
        descricao: defaultDescricao,
        material: 'Têxtil e aviamentos',
        preco: 83.65,
    },
    {
        id: 7,
        nome: 'Moda Essencial 07',
        categoria: 'Roupas, Calçados e Acessórios',
        slug: 'roupas-calcados-acessorios',
        imagem: '/img/Categorias/Roupas, Calçados e Acessórios/moda.jpg',
        descricao: defaultDescricao,
        material: 'Têxtil e aviamentos',
        preco: 86.4,
    },
    {
        id: 8,
        nome: 'Moda Essencial 08',
        categoria: 'Roupas, Calçados e Acessórios',
        slug: 'roupas-calcados-acessorios',
        imagem: '/img/Categorias/Roupas, Calçados e Acessórios/moda.jpg',
        descricao: defaultDescricao,
        material: 'Têxtil e aviamentos',
        preco: 89.15,
    },
    {
        id: 9,
        nome: 'Moda Essencial 09',
        categoria: 'Roupas, Calçados e Acessórios',
        slug: 'roupas-calcados-acessorios',
        imagem: '/img/Categorias/Roupas, Calçados e Acessórios/moda.jpg',
        descricao: defaultDescricao,
        material: 'Têxtil e aviamentos',
        preco: 91.9,
    },

    // Automotivo (10-19)
    {
        id: 10,
        nome: 'Kit Automotivo Essencial 01',
        categoria: 'Automotivo',
        slug: 'automotivo',
        imagem: '/img/Categorias/Automotivo/automotivo.jpg',
        descricao: defaultDescricao,
        material: 'Metal e polímeros',
        preco: 39.9,
    },
    {
        id: 11,
        nome: 'Kit Automotivo Essencial 02',
        categoria: 'Automotivo',
        slug: 'automotivo',
        imagem: '/img/Categorias/Automotivo/automotivo2.webp',
        descricao: defaultDescricao,
        material: 'Metal e polímeros',
        preco: 42.65,
    },
    {
        id: 12,
        nome: 'Kit Automotivo Essencial 03',
        categoria: 'Automotivo',
        slug: 'automotivo',
        imagem: '/img/Categorias/Automotivo/automotivo3.webp',
        descricao: defaultDescricao,
        material: 'Metal e polímeros',
        preco: 45.4,
    },
    {
        id: 13,
        nome: 'Kit Automotivo Essencial 04',
        categoria: 'Automotivo',
        slug: 'automotivo',
        imagem: '/img/Categorias/Automotivo/automotivo4.webp',
        descricao: defaultDescricao,
        material: 'Metal e polímeros',
        preco: 48.15,
    },
    {
        id: 14,
        nome: 'Kit Automotivo Essencial 05',
        categoria: 'Automotivo',
        slug: 'automotivo',
        imagem: '/img/Categorias/Automotivo/automotivo5.webp',
        descricao: defaultDescricao,
        material: 'Metal e polímeros',
        preco: 50.9,
    },
    {
        id: 15,
        nome: 'Kit Automotivo Essencial 06',
        categoria: 'Automotivo',
        slug: 'automotivo',
        imagem: '/img/Categorias/Automotivo/automotivo.jpg',
        descricao: defaultDescricao,
        material: 'Metal e polímeros',
        preco: 53.65,
    },
    {
        id: 16,
        nome: 'Kit Automotivo Essencial 07',
        categoria: 'Automotivo',
        slug: 'automotivo',
        imagem: '/img/Categorias/Automotivo/automotivo2.webp',
        descricao: defaultDescricao,
        material: 'Metal e polímeros',
        preco: 56.4,
    },
    {
        id: 17,
        nome: 'Kit Automotivo Essencial 08',
        categoria: 'Automotivo',
        slug: 'automotivo',
        imagem: '/img/Categorias/Automotivo/automotivo3.webp',
        descricao: defaultDescricao,
        material: 'Metal e polímeros',
        preco: 59.15,
    },
    {
        id: 18,
        nome: 'Kit Automotivo Essencial 09',
        categoria: 'Automotivo',
        slug: 'automotivo',
        imagem: '/img/Categorias/Automotivo/automotivo4.webp',
        descricao: defaultDescricao,
        material: 'Metal e polímeros',
        preco: 61.9,
    },
    {
        id: 19,
        nome: 'Kit Automotivo Essencial 10',
        categoria: 'Automotivo',
        slug: 'automotivo',
        imagem: '/img/Categorias/Automotivo/automotivo5.webp',
        descricao: defaultDescricao,
        material: 'Metal e polímeros',
        preco: 64.65,
    },

    // Beleza e Cuidados Pessoais (20-28)
    {
        id: 20,
        nome: 'Kit Beleza & Cuidados 01',
        categoria: 'Beleza e Cuidados Pessoais',
        slug: 'beleza-e-cuidados-pessoais',
        imagem: '/img/Categorias/Beleza e Cuidados Pessoais/batom.jpg',
        descricao: defaultDescricao,
        material: 'Cosméticos e embalagens recicláveis',
        preco: 49.9,
    },
    {
        id: 21,
        nome: 'Kit Beleza & Cuidados 02',
        categoria: 'Beleza e Cuidados Pessoais',
        slug: 'beleza-e-cuidados-pessoais',
        imagem: '/img/Categorias/Beleza e Cuidados Pessoais/beleza.webp',
        descricao: defaultDescricao,
        material: 'Cosméticos e embalagens recicláveis',
        preco: 52.65,
    },
    {
        id: 22,
        nome: 'Kit Beleza & Cuidados 03',
        categoria: 'Beleza e Cuidados Pessoais',
        slug: 'beleza-e-cuidados-pessoais',
        imagem: '/img/Categorias/Beleza e Cuidados Pessoais/beleza2.webp',
        descricao: defaultDescricao,
        material: 'Cosméticos e embalagens recicláveis',
        preco: 55.4,
    },
    {
        id: 23,
        nome: 'Kit Beleza & Cuidados 04',
        categoria: 'Beleza e Cuidados Pessoais',
        slug: 'beleza-e-cuidados-pessoais',
        imagem: '/img/Categorias/Beleza e Cuidados Pessoais/beleza3.webp',
        descricao: defaultDescricao,
        material: 'Cosméticos e embalagens recicláveis',
        preco: 58.15,
    },
    {
        id: 24,
        nome: 'Kit Beleza & Cuidados 05',
        categoria: 'Beleza e Cuidados Pessoais',
        slug: 'beleza-e-cuidados-pessoais',
        imagem: '/img/Categorias/Beleza e Cuidados Pessoais/beleza4.jpg',
        descricao: defaultDescricao,
        material: 'Cosméticos e embalagens recicláveis',
        preco: 60.9,
    },
    {
        id: 25,
        nome: 'Kit Beleza & Cuidados 06',
        categoria: 'Beleza e Cuidados Pessoais',
        slug: 'beleza-e-cuidados-pessoais',
        imagem: '/img/Categorias/Beleza e Cuidados Pessoais/batom.jpg',
        descricao: defaultDescricao,
        material: 'Cosméticos e embalagens recicláveis',
        preco: 63.65,
    },
    {
        id: 26,
        nome: 'Kit Beleza & Cuidados 07',
        categoria: 'Beleza e Cuidados Pessoais',
        slug: 'beleza-e-cuidados-pessoais',
        imagem: '/img/Categorias/Beleza e Cuidados Pessoais/beleza.webp',
        descricao: defaultDescricao,
        material: 'Cosméticos e embalagens recicláveis',
        preco: 66.4,
    },
    {
        id: 27,
        nome: 'Kit Beleza & Cuidados 08',
        categoria: 'Beleza e Cuidados Pessoais',
        slug: 'beleza-e-cuidados-pessoais',
        imagem: '/img/Categorias/Beleza e Cuidados Pessoais/beleza2.webp',
        descricao: defaultDescricao,
        material: 'Cosméticos e embalagens recicláveis',
        preco: 69.15,
    },
    {
        id: 28,
        nome: 'Kit Beleza & Cuidados 09',
        categoria: 'Beleza e Cuidados Pessoais',
        slug: 'beleza-e-cuidados-pessoais',
        imagem: '/img/Categorias/Beleza e Cuidados Pessoais/beleza3.webp',
        descricao: defaultDescricao,
        material: 'Cosméticos e embalagens recicláveis',
        preco: 71.9,
    },

    // Brinquedos e Jogos (29-37)
    {
        id: 29,
        nome: 'Brinquedo Educativo 01',
        categoria: 'Brinquedos e Jogos',
        slug: 'brinquedos-e-jogos',
        imagem: '/img/Categorias/Brinquedos e Jogos/brinquedos.jpg',
        descricao: defaultDescricao,
        material: 'Plástico atóxico',
        preco: 59.9,
    },
    {
        id: 30,
        nome: 'Brinquedo Educativo 02',
        categoria: 'Brinquedos e Jogos',
        slug: 'brinquedos-e-jogos',
        imagem: '/img/Categorias/Brinquedos e Jogos/jogos.webp',
        descricao: defaultDescricao,
        material: 'Plástico atóxico',
        preco: 62.65,
    },
    {
        id: 31,
        nome: 'Brinquedo Educativo 03',
        categoria: 'Brinquedos e Jogos',
        slug: 'brinquedos-e-jogos',
        imagem: '/img/Categorias/Brinquedos e Jogos/jogos2.webp',
        descricao: defaultDescricao,
        material: 'Plástico atóxico',
        preco: 65.4,
    },
    {
        id: 32,
        nome: 'Brinquedo Educativo 04',
        categoria: 'Brinquedos e Jogos',
        slug: 'brinquedos-e-jogos',
        imagem: '/img/Categorias/Brinquedos e Jogos/jogos3.webp',
        descricao: defaultDescricao,
        material: 'Plástico atóxico',
        preco: 68.15,
    },
    {
        id: 33,
        nome: 'Brinquedo Educativo 05',
        categoria: 'Brinquedos e Jogos',
        slug: 'brinquedos-e-jogos',
        imagem: '/img/Categorias/Brinquedos e Jogos/jogos4.webp',
        descricao: defaultDescricao,
        material: 'Plástico atóxico',
        preco: 70.9,
    },
    {
        id: 34,
        nome: 'Brinquedo Educativo 06',
        categoria: 'Brinquedos e Jogos',
        slug: 'brinquedos-e-jogos',
        imagem: '/img/Categorias/Brinquedos e Jogos/brinquedos.jpg',
        descricao: defaultDescricao,
        material: 'Plástico atóxico',
        preco: 73.65,
    },
    {
        id: 35,
        nome: 'Brinquedo Educativo 07',
        categoria: 'Brinquedos e Jogos',
        slug: 'brinquedos-e-jogos',
        imagem: '/img/Categorias/Brinquedos e Jogos/jogos.webp',
        descricao: defaultDescricao,
        material: 'Plástico atóxico',
        preco: 76.4,
    },
    {
        id: 36,
        nome: 'Brinquedo Educativo 08',
        categoria: 'Brinquedos e Jogos',
        slug: 'brinquedos-e-jogos',
        imagem: '/img/Categorias/Brinquedos e Jogos/jogos2.webp',
        descricao: defaultDescricao,
        material: 'Plástico atóxico',
        preco: 79.15,
    },
    {
        id: 37,
        nome: 'Brinquedo Educativo 09',
        categoria: 'Brinquedos e Jogos',
        slug: 'brinquedos-e-jogos',
        imagem: '/img/Categorias/Brinquedos e Jogos/jogos3.webp',
        descricao: defaultDescricao,
        material: 'Plástico atóxico',
        preco: 81.9,
    },

    // Casa, Jardim e Limpeza (38-46)
    {
        id: 38,
        nome: 'Item Casa & Jardim 01',
        categoria: 'Casa, Jardim e Limpeza',
        slug: 'casa-jardim-limpeza',
        imagem: '/img/Categorias/Casa, Jardim, e Limpeza/ventilador.jpg',
        descricao: defaultDescricao,
        material: 'Plástico e componentes metálicos',
        preco: 69.9,
    },
    {
        id: 39,
        nome: 'Item Casa & Jardim 02',
        categoria: 'Casa, Jardim e Limpeza',
        slug: 'casa-jardim-limpeza',
        imagem: '/img/Categorias/Casa, Jardim, e Limpeza/casa.webp',
        descricao: defaultDescricao,
        material: 'Plástico e componentes metálicos',
        preco: 72.65,
    },
    {
        id: 40,
        nome: 'Item Casa & Jardim 03',
        categoria: 'Casa, Jardim e Limpeza',
        slug: 'casa-jardim-limpeza',
        imagem: '/img/Categorias/Casa, Jardim, e Limpeza/casa2.webp',
        descricao: defaultDescricao,
        material: 'Plástico e componentes metálicos',
        preco: 75.4,
    },
    {
        id: 41,
        nome: 'Item Casa & Jardim 04',
        categoria: 'Casa, Jardim e Limpeza',
        slug: 'casa-jardim-limpeza',
        imagem: '/img/Categorias/Casa, Jardim, e Limpeza/casa3.webp',
        descricao: defaultDescricao,
        material: 'Plástico e componentes metálicos',
        preco: 78.15,
    },
    {
        id: 42,
        nome: 'Item Casa & Jardim 05',
        categoria: 'Casa, Jardim e Limpeza',
        slug: 'casa-jardim-limpeza',
        imagem: '/img/Categorias/Casa, Jardim, e Limpeza/casa4.webp',
        descricao: defaultDescricao,
        material: 'Plástico e componentes metálicos',
        preco: 80.9,
    },
    {
        id: 43,
        nome: 'Item Casa & Jardim 06',
        categoria: 'Casa, Jardim e Limpeza',
        slug: 'casa-jardim-limpeza',
        imagem: '/img/Categorias/Casa, Jardim, e Limpeza/casa5.webp',
        descricao: defaultDescricao,
        material: 'Plástico e componentes metálicos',
        preco: 83.65,
    },
    {
        id: 44,
        nome: 'Item Casa & Jardim 07',
        categoria: 'Casa, Jardim e Limpeza',
        slug: 'casa-jardim-limpeza',
        imagem: '/img/Categorias/Casa, Jardim, e Limpeza/ventilador.jpg',
        descricao: defaultDescricao,
        material: 'Plástico e componentes metálicos',
        preco: 86.4,
    },
    {
        id: 45,
        nome: 'Item Casa & Jardim 08',
        categoria: 'Casa, Jardim e Limpeza',
        slug: 'casa-jardim-limpeza',
        imagem: '/img/Categorias/Casa, Jardim, e Limpeza/casa.webp',
        descricao: defaultDescricao,
        material: 'Plástico e componentes metálicos',
        preco: 89.15,
    },
    {
        id: 46,
        nome: 'Item Casa & Jardim 09',
        categoria: 'Casa, Jardim e Limpeza',
        slug: 'casa-jardim-limpeza',
        imagem: '/img/Categorias/Casa, Jardim, e Limpeza/casa2.webp',
        descricao: defaultDescricao,
        material: 'Plástico e componentes metálicos',
        preco: 91.9,
    },

    // Cozinha (47-55)
    {
        id: 47,
        nome: 'Conjunto de Cozinha 01',
        categoria: 'Cozinha',
        slug: 'cozinha',
        imagem: '/img/Categorias/Cozinha/cozinha.jpg',
        descricao: defaultDescricao,
        material: 'Aço inox e silicone',
        preco: 79.9,
    },
    {
        id: 48,
        nome: 'Conjunto de Cozinha 02',
        categoria: 'Cozinha',
        slug: 'cozinha',
        imagem: '/img/Categorias/Cozinha/cozinha.webp',
        descricao: defaultDescricao,
        material: 'Aço inox e silicone',
        preco: 82.65,
    },
    {
        id: 49,
        nome: 'Conjunto de Cozinha 03',
        categoria: 'Cozinha',
        slug: 'cozinha',
        imagem: '/img/Categorias/Cozinha/cozinha2.webp',
        descricao: defaultDescricao,
        material: 'Aço inox e silicone',
        preco: 85.4,
    },
    {
        id: 50,
        nome: 'Conjunto de Cozinha 04',
        categoria: 'Cozinha',
        slug: 'cozinha',
        imagem: '/img/Categorias/Cozinha/cozinha3.webp',
        descricao: defaultDescricao,
        material: 'Aço inox e silicone',
        preco: 88.15,
    },
    {
        id: 51,
        nome: 'Conjunto de Cozinha 05',
        categoria: 'Cozinha',
        slug: 'cozinha',
        imagem: '/img/Categorias/Cozinha/cozinha4.webp',
        descricao: defaultDescricao,
        material: 'Aço inox e silicone',
        preco: 90.9,
    },
    {
        id: 52,
        nome: 'Conjunto de Cozinha 06',
        categoria: 'Cozinha',
        slug: 'cozinha',
        imagem: '/img/Categorias/Cozinha/cozinha5.webp',
        descricao: defaultDescricao,
        material: 'Aço inox e silicone',
        preco: 93.65,
    },
    {
        id: 53,
        nome: 'Conjunto de Cozinha 07',
        categoria: 'Cozinha',
        slug: 'cozinha',
        imagem: '/img/Categorias/Cozinha/cozinha.jpg',
        descricao: defaultDescricao,
        material: 'Aço inox e silicone',
        preco: 96.4,
    },
    {
        id: 54,
        nome: 'Conjunto de Cozinha 08',
        categoria: 'Cozinha',
        slug: 'cozinha',
        imagem: '/img/Categorias/Cozinha/cozinha.webp',
        descricao: defaultDescricao,
        material: 'Aço inox e silicone',
        preco: 99.15,
    },
    {
        id: 55,
        nome: 'Conjunto de Cozinha 09',
        categoria: 'Cozinha',
        slug: 'cozinha',
        imagem: '/img/Categorias/Cozinha/cozinha2.webp',
        descricao: defaultDescricao,
        material: 'Aço inox e silicone',
        preco: 101.9,
    },

    // Eletrônicos, TV e Áudio (56-64)
    {
        id: 56,
        nome: 'Acessório Eletrônico 01',
        categoria: 'Eletrônicos, TV e Áudio',
        slug: 'eletronicos-tv-audio',
        imagem: '/img/Categorias/Eletrônicos, TV, Áudio/eletrodomesticos.jpg',
        descricao: defaultDescricao,
        material: 'Componentes eletrônicos e polímeros',
        preco: 89.9,
    },
    {
        id: 57,
        nome: 'Acessório Eletrônico 02',
        categoria: 'Eletrônicos, TV e Áudio',
        slug: 'eletronicos-tv-audio',
        imagem: '/img/Categorias/Eletrônicos, TV, Áudio/tv1.webp',
        descricao: defaultDescricao,
        material: 'Componentes eletrônicos e polímeros',
        preco: 92.65,
    },
    {
        id: 58,
        nome: 'Acessório Eletrônico 03',
        categoria: 'Eletrônicos, TV e Áudio',
        slug: 'eletronicos-tv-audio',
        imagem: '/img/Categorias/Eletrônicos, TV, Áudio/tv2.webp',
        descricao: defaultDescricao,
        material: 'Componentes eletrônicos e polímeros',
        preco: 95.4,
    },
    {
        id: 59,
        nome: 'Acessório Eletrônico 04',
        categoria: 'Eletrônicos, TV e Áudio',
        slug: 'eletronicos-tv-audio',
        imagem: '/img/Categorias/Eletrônicos, TV, Áudio/tv3.jpg',
        descricao: defaultDescricao,
        material: 'Componentes eletrônicos e polímeros',
        preco: 98.15,
    },
    {
        id: 60,
        nome: 'Acessório Eletrônico 05',
        categoria: 'Eletrônicos, TV e Áudio',
        slug: 'eletronicos-tv-audio',
        imagem: '/img/Categorias/Eletrônicos, TV, Áudio/tv4.webp',
        descricao: defaultDescricao,
        material: 'Componentes eletrônicos e polímeros',
        preco: 100.9,
    },
    {
        id: 61,
        nome: 'Acessório Eletrônico 06',
        categoria: 'Eletrônicos, TV e Áudio',
        slug: 'eletronicos-tv-audio',
        imagem: '/img/Categorias/Eletrônicos, TV, Áudio/eletrodomesticos.jpg',
        descricao: defaultDescricao,
        material: 'Componentes eletrônicos e polímeros',
        preco: 103.65,
    },
    {
        id: 62,
        nome: 'Acessório Eletrônico 07',
        categoria: 'Eletrônicos, TV e Áudio',
        slug: 'eletronicos-tv-audio',
        imagem: '/img/Categorias/Eletrônicos, TV, Áudio/tv1.webp',
        descricao: defaultDescricao,
        material: 'Componentes eletrônicos e polímeros',
        preco: 106.4,
    },
    {
        id: 63,
        nome: 'Acessório Eletrônico 08',
        categoria: 'Eletrônicos, TV e Áudio',
        slug: 'eletronicos-tv-audio',
        imagem: '/img/Categorias/Eletrônicos, TV, Áudio/tv2.webp',
        descricao: defaultDescricao,
        material: 'Componentes eletrônicos e polímeros',
        preco: 109.15,
    },
    {
        id: 64,
        nome: 'Acessório Eletrônico 09',
        categoria: 'Eletrônicos, TV e Áudio',
        slug: 'eletronicos-tv-audio',
        imagem: '/img/Categorias/Eletrônicos, TV, Áudio/tv3.jpg',
        descricao: defaultDescricao,
        material: 'Componentes eletrônicos e polímeros',
        preco: 111.9,
    },

    // Esportes, Aventura e Lazer (65-73)
    {
        id: 65,
        nome: 'Acessório Esportivo 01',
        categoria: 'Esportes, Aventura e Lazer',
        slug: 'esportes-aventura-lazer',
        imagem: '/img/Categorias/Esportes, Aventura e Lazer/Esportes.jpg',
        descricao: defaultDescricao,
        material: 'Tecido e polímeros',
        preco: 59.9,
    },
    {
        id: 66,
        nome: 'Acessório Esportivo 02',
        categoria: 'Esportes, Aventura e Lazer',
        slug: 'esportes-aventura-lazer',
        imagem: '/img/Categorias/Esportes, Aventura e Lazer/Esportes.jpg',
        descricao: defaultDescricao,
        material: 'Tecido e polímeros',
        preco: 62.65,
    },
    {
        id: 67,
        nome: 'Acessório Esportivo 03',
        categoria: 'Esportes, Aventura e Lazer',
        slug: 'esportes-aventura-lazer',
        imagem: '/img/Categorias/Esportes, Aventura e Lazer/Esportes.jpg',
        descricao: defaultDescricao,
        material: 'Tecido e polímeros',
        preco: 65.4,
    },
    {
        id: 68,
        nome: 'Acessório Esportivo 04',
        categoria: 'Esportes, Aventura e Lazer',
        slug: 'esportes-aventura-lazer',
        imagem: '/img/Categorias/Esportes, Aventura e Lazer/Esportes.jpg',
        descricao: defaultDescricao,
        material: 'Tecido e polímeros',
        preco: 68.15,
    },
    {
        id: 69,
        nome: 'Acessório Esportivo 05',
        categoria: 'Esportes, Aventura e Lazer',
        slug: 'esportes-aventura-lazer',
        imagem: '/img/Categorias/Esportes, Aventura e Lazer/Esportes.jpg',
        descricao: defaultDescricao,
        material: 'Tecido e polímeros',
        preco: 70.9,
    },
    {
        id: 70,
        nome: 'Acessório Esportivo 06',
        categoria: 'Esportes, Aventura e Lazer',
        slug: 'esportes-aventura-lazer',
        imagem: '/img/Categorias/Esportes, Aventura e Lazer/Esportes.jpg',
        descricao: defaultDescricao,
        material: 'Tecido e polímeros',
        preco: 73.65,
    },
    {
        id: 71,
        nome: 'Acessório Esportivo 07',
        categoria: 'Esportes, Aventura e Lazer',
        slug: 'esportes-aventura-lazer',
        imagem: '/img/Categorias/Esportes, Aventura e Lazer/Esportes.jpg',
        descricao: defaultDescricao,
        material: 'Tecido e polímeros',
        preco: 76.4,
    },
    {
        id: 72,
        nome: 'Acessório Esportivo 08',
        categoria: 'Esportes, Aventura e Lazer',
        slug: 'esportes-aventura-lazer',
        imagem: '/img/Categorias/Esportes, Aventura e Lazer/Esportes.jpg',
        descricao: defaultDescricao,
        material: 'Tecido e polímeros',
        preco: 79.15,
    },
    {
        id: 73,
        nome: 'Acessório Esportivo 09',
        categoria: 'Esportes, Aventura e Lazer',
        slug: 'esportes-aventura-lazer',
        imagem: '/img/Categorias/Esportes, Aventura e Lazer/Esportes.jpg',
        descricao: defaultDescricao,
        material: 'Tecido e polímeros',
        preco: 81.9,
    },

    // Ferramentas e Construção (74-82)
    {
        id: 74,
        nome: 'Ferramenta Multiuso 01',
        categoria: 'Ferramentas e Construção',
        slug: 'ferramentas-e-construcao',
        imagem: '/img/Categorias/Ferramentas e Construção/ferramentas.jpg',
        descricao: defaultDescricao,
        material: 'Aço carbono',
        preco: 74.9,
    },
    {
        id: 75,
        nome: 'Ferramenta Multiuso 02',
        categoria: 'Ferramentas e Construção',
        slug: 'ferramentas-e-construcao',
        imagem: '/img/Categorias/Ferramentas e Construção/ferramentas.jpg',
        descricao: defaultDescricao,
        material: 'Aço carbono',
        preco: 77.65,
    },
    {
        id: 76,
        nome: 'Ferramenta Multiuso 03',
        categoria: 'Ferramentas e Construção',
        slug: 'ferramentas-e-construcao',
        imagem: '/img/Categorias/Ferramentas e Construção/ferramentas.jpg',
        descricao: defaultDescricao,
        material: 'Aço carbono',
        preco: 80.4,
    },
    {
        id: 77,
        nome: 'Ferramenta Multiuso 04',
        categoria: 'Ferramentas e Construção',
        slug: 'ferramentas-e-construcao',
        imagem: '/img/Categorias/Ferramentas e Construção/ferramentas.jpg',
        descricao: defaultDescricao,
        material: 'Aço carbono',
        preco: 83.15,
    },
    {
        id: 78,
        nome: 'Ferramenta Multiuso 05',
        categoria: 'Ferramentas e Construção',
        slug: 'ferramentas-e-construcao',
        imagem: '/img/Categorias/Ferramentas e Construção/ferramentas.jpg',
        descricao: defaultDescricao,
        material: 'Aço carbono',
        preco: 85.9,
    },
    {
        id: 79,
        nome: 'Ferramenta Multiuso 06',
        categoria: 'Ferramentas e Construção',
        slug: 'ferramentas-e-construcao',
        imagem: '/img/Categorias/Ferramentas e Construção/ferramentas.jpg',
        descricao: defaultDescricao,
        material: 'Aço carbono',
        preco: 88.65,
    },
    {
        id: 80,
        nome: 'Ferramenta Multiuso 07',
        categoria: 'Ferramentas e Construção',
        slug: 'ferramentas-e-construcao',
        imagem: '/img/Categorias/Ferramentas e Construção/ferramentas.jpg',
        descricao: defaultDescricao,
        material: 'Aço carbono',
        preco: 91.4,
    },
    {
        id: 81,
        nome: 'Ferramenta Multiuso 08',
        categoria: 'Ferramentas e Construção',
        slug: 'ferramentas-e-construcao',
        imagem: '/img/Categorias/Ferramentas e Construção/ferramentas.jpg',
        descricao: defaultDescricao,
        material: 'Aço carbono',
        preco: 94.15,
    },
    {
        id: 82,
        nome: 'Ferramenta Multiuso 09',
        categoria: 'Ferramentas e Construção',
        slug: 'ferramentas-e-construcao',
        imagem: '/img/Categorias/Ferramentas e Construção/ferramentas.jpg',
        descricao: defaultDescricao,
        material: 'Aço carbono',
        preco: 96.9,
    },

    // Games e Consoles (83-91)
    {
        id: 83,
        nome: 'Acessório Gamer 01',
        categoria: 'Games e Consoles',
        slug: 'games-e-consoles',
        imagem: '/img/Categorias/Games e Consoles/games.jpg',
        descricao: defaultDescricao,
        material: 'ABS e componentes eletrônicos',
        preco: 99.9,
    },
    {
        id: 84,
        nome: 'Acessório Gamer 02',
        categoria: 'Games e Consoles',
        slug: 'games-e-consoles',
        imagem: '/img/Categorias/Games e Consoles/games.jpg',
        descricao: defaultDescricao,
        material: 'ABS e componentes eletrônicos',
        preco: 102.65,
    },
    {
        id: 85,
        nome: 'Acessório Gamer 03',
        categoria: 'Games e Consoles',
        slug: 'games-e-consoles',
        imagem: '/img/Categorias/Games e Consoles/games.jpg',
        descricao: defaultDescricao,
        material: 'ABS e componentes eletrônicos',
        preco: 105.4,
    },
    {
        id: 86,
        nome: 'Acessório Gamer 04',
        categoria: 'Games e Consoles',
        slug: 'games-e-consoles',
        imagem: '/img/Categorias/Games e Consoles/games.jpg',
        descricao: defaultDescricao,
        material: 'ABS e componentes eletrônicos',
        preco: 108.15,
    },
    {
        id: 87,
        nome: 'Acessório Gamer 05',
        categoria: 'Games e Consoles',
        slug: 'games-e-consoles',
        imagem: '/img/Categorias/Games e Consoles/games.jpg',
        descricao: defaultDescricao,
        material: 'ABS e componentes eletrônicos',
        preco: 110.9,
    },
    {
        id: 88,
        nome: 'Acessório Gamer 06',
        categoria: 'Games e Consoles',
        slug: 'games-e-consoles',
        imagem: '/img/Categorias/Games e Consoles/games.jpg',
        descricao: defaultDescricao,
        material: 'ABS e componentes eletrônicos',
        preco: 113.65,
    },
    {
        id: 89,
        nome: 'Acessório Gamer 07',
        categoria: 'Games e Consoles',
        slug: 'games-e-consoles',
        imagem: '/img/Categorias/Games e Consoles/games.jpg',
        descricao: defaultDescricao,
        material: 'ABS e componentes eletrônicos',
        preco: 116.4,
    },
    {
        id: 90,
        nome: 'Acessório Gamer 08',
        categoria: 'Games e Consoles',
        slug: 'games-e-consoles',
        imagem: '/img/Categorias/Games e Consoles/games.jpg',
        descricao: defaultDescricao,
        material: 'ABS e componentes eletrônicos',
        preco: 119.15,
    },
    {
        id: 91,
        nome: 'Acessório Gamer 09',
        categoria: 'Games e Consoles',
        slug: 'games-e-consoles',
        imagem: '/img/Categorias/Games e Consoles/games.jpg',
        descricao: defaultDescricao,
        material: 'ABS e componentes eletrônicos',
        preco: 121.9,
    },

    // Livros (92-100)
    {
        id: 92,
        nome: 'Livro Destaque 01',
        categoria: 'Livros',
        slug: 'livros',
        imagem: '/img/Categorias/Livros/livros.jpg',
        descricao: defaultDescricao,
        material: 'Papel e capa cartonada',
        preco: 34.9,
    },
    {
        id: 93,
        nome: 'Livro Destaque 02',
        categoria: 'Livros',
        slug: 'livros',
        imagem: '/img/Categorias/Livros/livros.jpg',
        descricao: defaultDescricao,
        material: 'Papel e capa cartonada',
        preco: 37.65,
    },
    {
        id: 94,
        nome: 'Livro Destaque 03',
        categoria: 'Livros',
        slug: 'livros',
        imagem: '/img/Categorias/Livros/livros.jpg',
        descricao: defaultDescricao,
        material: 'Papel e capa cartonada',
        preco: 40.4,
    },
    {
        id: 95,
        nome: 'Livro Destaque 04',
        categoria: 'Livros',
        slug: 'livros',
        imagem: '/img/Categorias/Livros/livros.jpg',
        descricao: defaultDescricao,
        material: 'Papel e capa cartonada',
        preco: 43.15,
    },
    {
        id: 96,
        nome: 'Livro Destaque 05',
        categoria: 'Livros',
        slug: 'livros',
        imagem: '/img/Categorias/Livros/livros.jpg',
        descricao: defaultDescricao,
        material: 'Papel e capa cartonada',
        preco: 45.9,
    },
    {
        id: 97,
        nome: 'Livro Destaque 06',
        categoria: 'Livros',
        slug: 'livros',
        imagem: '/img/Categorias/Livros/livros.jpg',
        descricao: defaultDescricao,
        material: 'Papel e capa cartonada',
        preco: 48.65,
    },
    {
        id: 98,
        nome: 'Livro Destaque 07',
        categoria: 'Livros',
        slug: 'livros',
        imagem: '/img/Categorias/Livros/livros.jpg',
        descricao: defaultDescricao,
        material: 'Papel e capa cartonada',
        preco: 51.4,
    },
    {
        id: 99,
        nome: 'Livro Destaque 08',
        categoria: 'Livros',
        slug: 'livros',
        imagem: '/img/Categorias/Livros/livros.jpg',
        descricao: defaultDescricao,
        material: 'Papel e capa cartonada',
        preco: 54.15,
    },
    {
        id: 100,
        nome: 'Livro Destaque 09',
        categoria: 'Livros',
        slug: 'livros',
        imagem: '/img/Categorias/Livros/livros.jpg',
        descricao: defaultDescricao,
        material: 'Papel e capa cartonada',
        preco: 56.9,
    },

    // Bebês (110-118)
    {
        id: 110,
        nome: 'Bebê Conforto 01',
        categoria: 'Bebês',
        slug: 'bebes',
        imagem: '/img/Categorias/Bebês/bebes.webp',
        descricao: defaultDescricao,
        material: 'Tecido e materiais infantis',
        preco: 49.9,
    },
    {
        id: 111,
        nome: 'Bebê Conforto 02',
        categoria: 'Bebês',
        slug: 'bebes',
        imagem: '/img/Categorias/Bebês/bebes.webp',
        descricao: defaultDescricao,
        material: 'Tecido e materiais infantis',
        preco: 52.65,
    },
    {
        id: 112,
        nome: 'Bebê Conforto 03',
        categoria: 'Bebês',
        slug: 'bebes',
        imagem: '/img/Categorias/Bebês/bebes.webp',
        descricao: defaultDescricao,
        material: 'Tecido e materiais infantis',
        preco: 55.4,
    },
    {
        id: 113,
        nome: 'Bebê Conforto 04',
        categoria: 'Bebês',
        slug: 'bebes',
        imagem: '/img/Categorias/Bebês/bebes.webp',
        descricao: defaultDescricao,
        material: 'Tecido e materiais infantis',
        preco: 58.15,
    },
    {
        id: 114,
        nome: 'Bebê Conforto 05',
        categoria: 'Bebês',
        slug: 'bebes',
        imagem: '/img/Categorias/Bebês/bebes.webp',
        descricao: defaultDescricao,
        material: 'Tecido e materiais infantis',
        preco: 60.9,
    },
    {
        id: 115,
        nome: 'Bebê Conforto 06',
        categoria: 'Bebês',
        slug: 'bebes',
        imagem: '/img/Categorias/Bebês/bebes.webp',
        descricao: defaultDescricao,
        material: 'Tecido e materiais infantis',
        preco: 63.65,
    },
    {
        id: 116,
        nome: 'Bebê Conforto 07',
        categoria: 'Bebês',
        slug: 'bebes',
        imagem: '/img/Categorias/Bebês/bebes.webp',
        descricao: defaultDescricao,
        material: 'Tecido e materiais infantis',
        preco: 66.4,
    },
    {
        id: 117,
        nome: 'Bebê Conforto 08',
        categoria: 'Bebês',
        slug: 'bebes',
        imagem: '/img/Categorias/Bebês/bebes.webp',
        descricao: defaultDescricao,
        material: 'Tecido e materiais infantis',
        preco: 69.15,
    },
    {
        id: 118,
        nome: 'Bebê Conforto 09',
        categoria: 'Bebês',
        slug: 'bebes',
        imagem: '/img/Categorias/Bebês/bebes.webp',
        descricao: defaultDescricao,
        material: 'Tecido e materiais infantis',
        preco: 71.9,
    },

    // Bolsas, Malas e Mochilas (119-127)
    {
        id: 119,
        nome: 'Bolsa & Mochila 01',
        categoria: 'Bolsas, Malas e Mochilas',
        slug: 'bolsas-malas-mochilas',
        imagem: '/img/Categorias/Bolsas, Malas e Mochilas/mala.webp',
        descricao: defaultDescricao,
        material: 'Poliéster e zíper reforçado',
        preco: 89.9,
    },
    {
        id: 120,
        nome: 'Bolsa & Mochila 02',
        categoria: 'Bolsas, Malas e Mochilas',
        slug: 'bolsas-malas-mochilas',
        imagem: '/img/Categorias/Bolsas, Malas e Mochilas/mala.webp',
        descricao: defaultDescricao,
        material: 'Poliéster e zíper reforçado',
        preco: 92.65,
    },
    {
        id: 121,
        nome: 'Bolsa & Mochila 03',
        categoria: 'Bolsas, Malas e Mochilas',
        slug: 'bolsas-malas-mochilas',
        imagem: '/img/Categorias/Bolsas, Malas e Mochilas/mala.webp',
        descricao: defaultDescricao,
        material: 'Poliéster e zíper reforçado',
        preco: 95.4,
    },
    {
        id: 122,
        nome: 'Bolsa & Mochila 04',
        categoria: 'Bolsas, Malas e Mochilas',
        slug: 'bolsas-malas-mochilas',
        imagem: '/img/Categorias/Bolsas, Malas e Mochilas/mala.webp',
        descricao: defaultDescricao,
        material: 'Poliéster e zíper reforçado',
        preco: 98.15,
    },
    {
        id: 123,
        nome: 'Bolsa & Mochila 05',
        categoria: 'Bolsas, Malas e Mochilas',
        slug: 'bolsas-malas-mochilas',
        imagem: '/img/Categorias/Bolsas, Malas e Mochilas/mala.webp',
        descricao: defaultDescricao,
        material: 'Poliéster e zíper reforçado',
        preco: 100.9,
    },
    {
        id: 124,
        nome: 'Bolsa & Mochila 06',
        categoria: 'Bolsas, Malas e Mochilas',
        slug: 'bolsas-malas-mochilas',
        imagem: '/img/Categorias/Bolsas, Malas e Mochilas/mala.webp',
        descricao: defaultDescricao,
        material: 'Poliéster e zíper reforçado',
        preco: 103.65,
    },
    {
        id: 125,
        nome: 'Bolsa & Mochila 07',
        categoria: 'Bolsas, Malas e Mochilas',
        slug: 'bolsas-malas-mochilas',
        imagem: '/img/Categorias/Bolsas, Malas e Mochilas/mala.webp',
        descricao: defaultDescricao,
        material: 'Poliéster e zíper reforçado',
        preco: 106.4,
    },
    {
        id: 126,
        nome: 'Bolsa & Mochila 08',
        categoria: 'Bolsas, Malas e Mochilas',
        slug: 'bolsas-malas-mochilas',
        imagem: '/img/Categorias/Bolsas, Malas e Mochilas/mala.webp',
        descricao: defaultDescricao,
        material: 'Poliéster e zíper reforçado',
        preco: 109.15,
    },
    {
        id: 127,
        nome: 'Bolsa & Mochila 09',
        categoria: 'Bolsas, Malas e Mochilas',
        slug: 'bolsas-malas-mochilas',
        imagem: '/img/Categorias/Bolsas, Malas e Mochilas/mala.webp',
        descricao: defaultDescricao,
        material: 'Poliéster e zíper reforçado',
        preco: 111.9,
    },

    // Celulares e Comunicação (128-136)
    {
        id: 128,
        nome: 'Acessório Mobile 01',
        categoria: 'Celulares e Comunicação',
        slug: 'celulares-e-comunicacao',
        imagem: '/img/Categorias/Celulares e Comunicação/celular.jpg',
        descricao: defaultDescricao,
        material: 'ABS e silicone',
        preco: 29.9,
    },
    {
        id: 129,
        nome: 'Acessório Mobile 02',
        categoria: 'Celulares e Comunicação',
        slug: 'celulares-e-comunicacao',
        imagem: '/img/Categorias/Celulares e Comunicação/celular.jpg',
        descricao: defaultDescricao,
        material: 'ABS e silicone',
        preco: 32.65,
    },
    {
        id: 130,
        nome: 'Acessório Mobile 03',
        categoria: 'Celulares e Comunicação',
        slug: 'celulares-e-comunicacao',
        imagem: '/img/Categorias/Celulares e Comunicação/celular.jpg',
        descricao: defaultDescricao,
        material: 'ABS e silicone',
        preco: 35.4,
    },
    {
        id: 131,
        nome: 'Acessório Mobile 04',
        categoria: 'Celulares e Comunicação',
        slug: 'celulares-e-comunicacao',
        imagem: '/img/Categorias/Celulares e Comunicação/celular.jpg',
        descricao: defaultDescricao,
        material: 'ABS e silicone',
        preco: 38.15,
    },
    {
        id: 132,
        nome: 'Acessório Mobile 05',
        categoria: 'Celulares e Comunicação',
        slug: 'celulares-e-comunicacao',
        imagem: '/img/Categorias/Celulares e Comunicação/celular.jpg',
        descricao: defaultDescricao,
        material: 'ABS e silicone',
        preco: 40.9,
    },
    {
        id: 133,
        nome: 'Acessório Mobile 06',
        categoria: 'Celulares e Comunicação',
        slug: 'celulares-e-comunicacao',
        imagem: '/img/Categorias/Celulares e Comunicação/celular.jpg',
        descricao: defaultDescricao,
        material: 'ABS e silicone',
        preco: 43.65,
    },
    {
        id: 134,
        nome: 'Acessório Mobile 07',
        categoria: 'Celulares e Comunicação',
        slug: 'celulares-e-comunicacao',
        imagem: '/img/Categorias/Celulares e Comunicação/celular.jpg',
        descricao: defaultDescricao,
        material: 'ABS e silicone',
        preco: 46.4,
    },
    {
        id: 135,
        nome: 'Acessório Mobile 08',
        categoria: 'Celulares e Comunicação',
        slug: 'celulares-e-comunicacao',
        imagem: '/img/Categorias/Celulares e Comunicação/celular.jpg',
        descricao: defaultDescricao,
        material: 'ABS e silicone',
        preco: 49.15,
    },
    {
        id: 136,
        nome: 'Acessório Mobile 09',
        categoria: 'Celulares e Comunicação',
        slug: 'celulares-e-comunicacao',
        imagem: '/img/Categorias/Celulares e Comunicação/celular.jpg',
        descricao: defaultDescricao,
        material: 'ABS e silicone',
        preco: 51.9,
    },

    // Computadores e Informática (137-145)
    {
        id: 137,
        nome: 'Acessório de Informática 01',
        categoria: 'Computadores e Informática',
        slug: 'computadores-e-informatica',
        imagem: '/img/Categorias/Computadores e Informática/computador.jpg',
        descricao: defaultDescricao,
        material: 'Plástico e componentes eletrônicos',
        preco: 59.9,
    },
    {
        id: 138,
        nome: 'Acessório de Informática 02',
        categoria: 'Computadores e Informática',
        slug: 'computadores-e-informatica',
        imagem: '/img/Categorias/Computadores e Informática/computador.jpg',
        descricao: defaultDescricao,
        material: 'Plástico e componentes eletrônicos',
        preco: 62.65,
    },
    {
        id: 139,
        nome: 'Acessório de Informática 03',
        categoria: 'Computadores e Informática',
        slug: 'computadores-e-informatica',
        imagem: '/img/Categorias/Computadores e Informática/computador.jpg',
        descricao: defaultDescricao,
        material: 'Plástico e componentes eletrônicos',
        preco: 65.4,
    },
    {
        id: 140,
        nome: 'Acessório de Informática 04',
        categoria: 'Computadores e Informática',
        slug: 'computadores-e-informatica',
        imagem: '/img/Categorias/Computadores e Informática/computador.jpg',
        descricao: defaultDescricao,
        material: 'Plástico e componentes eletrônicos',
        preco: 68.15,
    },
    {
        id: 141,
        nome: 'Acessório de Informática 05',
        categoria: 'Computadores e Informática',
        slug: 'computadores-e-informatica',
        imagem: '/img/Categorias/Computadores e Informática/computador.jpg',
        descricao: defaultDescricao,
        material: 'Plástico e componentes eletrônicos',
        preco: 70.9,
    },
    {
        id: 142,
        nome: 'Acessório de Informática 06',
        categoria: 'Computadores e Informática',
        slug: 'computadores-e-informatica',
        imagem: '/img/Categorias/Computadores e Informática/computador.jpg',
        descricao: defaultDescricao,
        material: 'Plástico e componentes eletrônicos',
        preco: 73.65,
    },
    {
        id: 143,
        nome: 'Acessório de Informática 07',
        categoria: 'Computadores e Informática',
        slug: 'computadores-e-informatica',
        imagem: '/img/Categorias/Computadores e Informática/computador.jpg',
        descricao: defaultDescricao,
        material: 'Plástico e componentes eletrônicos',
        preco: 76.4,
    },
    {
        id: 144,
        nome: 'Acessório de Informática 08',
        categoria: 'Computadores e Informática',
        slug: 'computadores-e-informatica',
        imagem: '/img/Categorias/Computadores e Informática/computador.jpg',
        descricao: defaultDescricao,
        material: 'Plástico e componentes eletrônicos',
        preco: 79.15,
    },
    {
        id: 145,
        nome: 'Acessório de Informática 09',
        categoria: 'Computadores e Informática',
        slug: 'computadores-e-informatica',
        imagem: '/img/Categorias/Computadores e Informática/computador.jpg',
        descricao: defaultDescricao,
        material: 'Plástico e componentes eletrônicos',
        preco: 81.9,
    },

    // Filmes, Séries e Música (146-154)
    {
        id: 146,
        nome: 'Colecionável Pop 01',
        categoria: 'Filmes, Séries e Música',
        slug: 'filmes-series-musica',
        imagem: '/img/Categorias/Filmes, Séries e Música/filmes.jpg',
        descricao: defaultDescricao,
        material: 'PVC e papel',
        preco: 39.9,
    },
    {
        id: 147,
        nome: 'Colecionável Pop 02',
        categoria: 'Filmes, Séries e Música',
        slug: 'filmes-series-musica',
        imagem: '/img/Categorias/Filmes, Séries e Música/filmes.jpg',
        descricao: defaultDescricao,
        material: 'PVC e papel',
        preco: 42.65,
    },
    {
        id: 148,
        nome: 'Colecionável Pop 03',
        categoria: 'Filmes, Séries e Música',
        slug: 'filmes-series-musica',
        imagem: '/img/Categorias/Filmes, Séries e Música/filmes.jpg',
        descricao: defaultDescricao,
        material: 'PVC e papel',
        preco: 45.4,
    },
    {
        id: 149,
        nome: 'Colecionável Pop 04',
        categoria: 'Filmes, Séries e Música',
        slug: 'filmes-series-musica',
        imagem: '/img/Categorias/Filmes, Séries e Música/filmes.jpg',
        descricao: defaultDescricao,
        material: 'PVC e papel',
        preco: 48.15,
    },
    {
        id: 150,
        nome: 'Colecionável Pop 05',
        categoria: 'Filmes, Séries e Música',
        slug: 'filmes-series-musica',
        imagem: '/img/Categorias/Filmes, Séries e Música/filmes.jpg',
        descricao: defaultDescricao,
        material: 'PVC e papel',
        preco: 50.9,
    },
    {
        id: 151,
        nome: 'Colecionável Pop 06',
        categoria: 'Filmes, Séries e Música',
        slug: 'filmes-series-musica',
        imagem: '/img/Categorias/Filmes, Séries e Música/filmes.jpg',
        descricao: defaultDescricao,
        material: 'PVC e papel',
        preco: 53.65,
    },
    {
        id: 152,
        nome: 'Colecionável Pop 07',
        categoria: 'Filmes, Séries e Música',
        slug: 'filmes-series-musica',
        imagem: '/img/Categorias/Filmes, Séries e Música/filmes.jpg',
        descricao: defaultDescricao,
        material: 'PVC e papel',
        preco: 56.4,
    },
    {
        id: 153,
        nome: 'Colecionável Pop 08',
        categoria: 'Filmes, Séries e Música',
        slug: 'filmes-series-musica',
        imagem: '/img/Categorias/Filmes, Séries e Música/filmes.jpg',
        descricao: defaultDescricao,
        material: 'PVC e papel',
        preco: 59.15,
    },
    {
        id: 154,
        nome: 'Colecionável Pop 09',
        categoria: 'Filmes, Séries e Música',
        slug: 'filmes-series-musica',
        imagem: '/img/Categorias/Filmes, Séries e Música/filmes.jpg',
        descricao: defaultDescricao,
        material: 'PVC e papel',
        preco: 61.9,
    },

    // Papelaria e Escritório (155-163)
    {
        id: 155,
        nome: 'Papelaria Essencial 01',
        categoria: 'Papelaria e Escritório',
        slug: 'papelaria-e-escritorio',
        imagem: '/img/Categorias/Papelaria e Escritório/papel.webp',
        descricao: defaultDescricao,
        material: 'Papel e plástico',
        preco: 12.9,
    },
    {
        id: 156,
        nome: 'Papelaria Essencial 02',
        categoria: 'Papelaria e Escritório',
        slug: 'papelaria-e-escritorio',
        imagem: '/img/Categorias/Papelaria e Escritório/papel.webp',
        descricao: defaultDescricao,
        material: 'Papel e plástico',
        preco: 15.65,
    },
    {
        id: 157,
        nome: 'Papelaria Essencial 03',
        categoria: 'Papelaria e Escritório',
        slug: 'papelaria-e-escritorio',
        imagem: '/img/Categorias/Papelaria e Escritório/papel.webp',
        descricao: defaultDescricao,
        material: 'Papel e plástico',
        preco: 18.4,
    },
    {
        id: 158,
        nome: 'Papelaria Essencial 04',
        categoria: 'Papelaria e Escritório',
        slug: 'papelaria-e-escritorio',
        imagem: '/img/Categorias/Papelaria e Escritório/papel.webp',
        descricao: defaultDescricao,
        material: 'Papel e plástico',
        preco: 21.15,
    },
    {
        id: 159,
        nome: 'Papelaria Essencial 05',
        categoria: 'Papelaria e Escritório',
        slug: 'papelaria-e-escritorio',
        imagem: '/img/Categorias/Papelaria e Escritório/papel.webp',
        descricao: defaultDescricao,
        material: 'Papel e plástico',
        preco: 23.9,
    },
    {
        id: 160,
        nome: 'Papelaria Essencial 06',
        categoria: 'Papelaria e Escritório',
        slug: 'papelaria-e-escritorio',
        imagem: '/img/Categorias/Papelaria e Escritório/papel.webp',
        descricao: defaultDescricao,
        material: 'Papel e plástico',
        preco: 26.65,
    },
    {
        id: 161,
        nome: 'Papelaria Essencial 07',
        categoria: 'Papelaria e Escritório',
        slug: 'papelaria-e-escritorio',
        imagem: '/img/Categorias/Papelaria e Escritório/papel.webp',
        descricao: defaultDescricao,
        material: 'Papel e plástico',
        preco: 29.4,
    },
    {
        id: 162,
        nome: 'Papelaria Essencial 08',
        categoria: 'Papelaria e Escritório',
        slug: 'papelaria-e-escritorio',
        imagem: '/img/Categorias/Papelaria e Escritório/papel.webp',
        descricao: defaultDescricao,
        material: 'Papel e plástico',
        preco: 32.15,
    },
    {
        id: 163,
        nome: 'Papelaria Essencial 09',
        categoria: 'Papelaria e Escritório',
        slug: 'papelaria-e-escritorio',
        imagem: '/img/Categorias/Papelaria e Escritório/papel.webp',
        descricao: defaultDescricao,
        material: 'Papel e plástico',
        preco: 34.9,
    },

    // Pet Shop (164-172)
    {
        id: 164,
        nome: 'Pet Essencial 01',
        categoria: 'Pet Shop',
        slug: 'pet-shop',
        imagem: '/img/Categorias/Pet Shop/pet.webp',
        descricao: defaultDescricao,
        material: 'Tecido e borracha',
        preco: 24.9,
    },
    {
        id: 165,
        nome: 'Pet Essencial 02',
        categoria: 'Pet Shop',
        slug: 'pet-shop',
        imagem: '/img/Categorias/Pet Shop/pet.webp',
        descricao: defaultDescricao,
        material: 'Tecido e borracha',
        preco: 27.65,
    },
    {
        id: 166,
        nome: 'Pet Essencial 03',
        categoria: 'Pet Shop',
        slug: 'pet-shop',
        imagem: '/img/Categorias/Pet Shop/pet.webp',
        descricao: defaultDescricao,
        material: 'Tecido e borracha',
        preco: 30.4,
    },
    {
        id: 167,
        nome: 'Pet Essencial 04',
        categoria: 'Pet Shop',
        slug: 'pet-shop',
        imagem: '/img/Categorias/Pet Shop/pet.webp',
        descricao: defaultDescricao,
        material: 'Tecido e borracha',
        preco: 33.15,
    },
    {
        id: 168,
        nome: 'Pet Essencial 05',
        categoria: 'Pet Shop',
        slug: 'pet-shop',
        imagem: '/img/Categorias/Pet Shop/pet.webp',
        descricao: defaultDescricao,
        material: 'Tecido e borracha',
        preco: 35.9,
    },
    {
        id: 169,
        nome: 'Pet Essencial 06',
        categoria: 'Pet Shop',
        slug: 'pet-shop',
        imagem: '/img/Categorias/Pet Shop/pet.webp',
        descricao: defaultDescricao,
        material: 'Tecido e borracha',
        preco: 38.65,
    },
    {
        id: 170,
        nome: 'Pet Essencial 07',
        categoria: 'Pet Shop',
        slug: 'pet-shop',
        imagem: '/img/Categorias/Pet Shop/pet.webp',
        descricao: defaultDescricao,
        material: 'Tecido e borracha',
        preco: 41.4,
    },
    {
        id: 171,
        nome: 'Pet Essencial 08',
        categoria: 'Pet Shop',
        slug: 'pet-shop',
        imagem: '/img/Categorias/Pet Shop/pet.webp',
        descricao: defaultDescricao,
        material: 'Tecido e borracha',
        preco: 44.15,
    },
    {
        id: 172,
        nome: 'Pet Essencial 09',
        categoria: 'Pet Shop',
        slug: 'pet-shop',
        imagem: '/img/Categorias/Pet Shop/pet.webp',
        descricao: defaultDescricao,
        material: 'Tecido e borracha',
        preco: 46.9,
    },
];



export const products: Product[] = applyCategoryImages(rawProducts);

// Funções para gerar listas de produtos dinâmicos por categoria

export function getBestSellersInFashion() {
    return products.filter(product => product.categoria === 'Roupas, Calçados e Acessórios').slice(0, 5);
}

export function getBestSellersInHome() {
    return products.filter(product => product.categoria === 'Casa, Jardim e Limpeza').slice(0, 5);
}

export function getBestPricesInStationery() {
    return products.filter(product => product.categoria === 'Papelaria e Escritório').sort((a, b) => a.preco - b.preco).slice(0, 5);
}

export function getTopRatedInBeauty() {
    return products.filter(product => product.categoria === 'Beleza e Cuidados Pessoais').slice(0, 5);
}

export function getTrendingInElectronics() {
    return products.filter(product => product.categoria === 'Eletrônicos, TV e Áudio').slice(0, 5);
}

export function getPopularInToys() {
    return products.filter(product => product.categoria === 'Brinquedos e Jogos').slice(0, 5);
}

export function getEssentialsInKitchen() {
    return products.filter(product => product.categoria === 'Cozinha').slice(0, 5);
}

export function getFavoritesInBooks() {
    return products.filter(product => product.categoria === 'Livros').slice(0, 5);
}

export function getDealsInAutomotive() {
    return products.filter(product => product.categoria === 'Automotivo').sort((a, b) => a.preco - b.preco).slice(0, 5);
}

export function getHighlightsInSports() {
    return products.filter(product => product.categoria === 'Esportes, Aventura e Lazer').slice(0, 5);
}

